{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "$_86.JPG\n",
      "capturing\n",
      "2000\n",
      "gas-cylinder-size-guide.jpg\n",
      "capturing\n",
      "2000\n",
      "gas-cylinder-size-guide_2.jpg\n",
      "capturing\n",
      "2000\n",
      "image_101.png\n",
      "capturing\n",
      "2000\n",
      "image_102.png\n",
      "capturing\n",
      "2000\n",
      "image_112.png\n",
      "capturing\n",
      "2000\n",
      "image_114.png\n",
      "capturing\n",
      "2000\n",
      "image_124.png\n",
      "capturing\n",
      "2000\n",
      "image_125.png\n",
      "capturing\n",
      "2000\n",
      "image_126.png\n",
      "capturing\n",
      "2000\n",
      "image_37.png\n",
      "capturing\n",
      "2000\n",
      "image_38.png\n",
      "capturing\n",
      "2000\n",
      "image_39.png\n",
      "capturing\n",
      "2000\n",
      "image_40.png\n",
      "capturing\n",
      "2000\n",
      "image_42.png\n",
      "capturing\n",
      "2000\n",
      "image_52.png\n",
      "capturing\n",
      "2000\n",
      "image_53.png\n",
      "capturing\n",
      "2000\n",
      "image_54.png\n",
      "capturing\n",
      "2000\n",
      "image_55.png\n",
      "capturing\n",
      "2000\n",
      "image_62.png\n",
      "capturing\n",
      "2000\n",
      "image_63.png\n",
      "capturing\n",
      "2000\n",
      "image_64.png\n",
      "capturing\n",
      "2000\n",
      "image_65.png\n",
      "capturing\n",
      "2000\n",
      "image_66.png\n",
      "capturing\n",
      "2000\n",
      "image_77.png\n",
      "capturing\n",
      "2000\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 1558, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"c:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\", line 605, in callit\n",
      "    func(*args)\n",
      "TypeError: loopCapture() missing 1 required positional argument: 'image_path'\n"
     ]
    }
   ],
   "source": [
    "import urllib.request, urllib.error, urllib.parse, base64\n",
    "from PIL import Image,ImageTk\n",
    "import io\n",
    "import tkinter, os, time\n",
    "\n",
    "#File names\n",
    "ROOT_DIR = os.path.abspath(\"../\")\n",
    "# Directory of images to run detection on\n",
    "IMAGE_DIR = os.path.join(ROOT_DIR, \"images\")\n",
    "file_names = os.listdir(IMAGE_DIR)\n",
    "\n",
    "root = tkinter.Tk()\n",
    "label = tkinter.Label(root)\n",
    "label.pack()\n",
    "img = None\n",
    "tkimg = [None]  # This, or something like it, is necessary because \n",
    "# if you do not keep a reference to PhotoImage instances, they get garbage collected.\n",
    "\n",
    "delay = 2000   # in milliseconds\n",
    "def loopCapture(image_path):\n",
    "    print(\"capturing\")\n",
    "    tkimg[0] = ImageTk.PhotoImage(Image.open(image_path))\n",
    "    label.config(image=tkimg[0])\n",
    "    root.update_idletasks()\n",
    "    root.after(delay, loopCapture)\n",
    "    print(delay)\n",
    "\n",
    "for image_name in file_names:\n",
    "    #time.sleep(10)\n",
    "    print(image_name)\n",
    "    loopCapture((os.path.join(IMAGE_DIR, image_name)))\n",
    "\n",
    "#loopCapture('masked_HighresScreenshot00071.png')\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "capturing\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Too early to create image",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-2-d3859679e41b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mloopCapture\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'masked_HighresScreenshot00071.png'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-1-edb181e87b0b>\u001b[0m in \u001b[0;36mloopCapture\u001b[1;34m(image_path)\u001b[0m\n\u001b[0;32m     20\u001b[0m \u001b[1;32mdef\u001b[0m \u001b[0mloopCapture\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mimage_path\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     21\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"capturing\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 22\u001b[1;33m     \u001b[0mtkimg\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mImageTk\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mPhotoImage\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mImage\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mopen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mimage_path\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     23\u001b[0m     \u001b[0mlabel\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mimage\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtkimg\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     24\u001b[0m     \u001b[0mroot\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate_idletasks\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\site-packages\\PIL\\ImageTk.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, image, size, **kw)\u001b[0m\n\u001b[0;32m    122\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__mode\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmode\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    123\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__size\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msize\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 124\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__photo\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtkinter\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mPhotoImage\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkw\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    125\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtk\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__photo\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtk\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    126\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mimage\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, name, cnf, master, **kw)\u001b[0m\n\u001b[0;32m   3400\u001b[0m         \u001b[0mValid\u001b[0m \u001b[0mresource\u001b[0m \u001b[0mnames\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mdata\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mformat\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mgamma\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheight\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpalette\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3401\u001b[0m         width.\"\"\"\n\u001b[1;32m-> 3402\u001b[1;33m         \u001b[0mImage\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__init__\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'photo'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcnf\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmaster\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkw\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3403\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mblank\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3404\u001b[0m         \u001b[1;34m\"\"\"Display a transparent image.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\16232668\\appdata\\local\\conda\\conda\\envs\\tensorflow\\lib\\tkinter\\__init__.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, imgtype, name, cnf, master, **kw)\u001b[0m\n\u001b[0;32m   3341\u001b[0m             \u001b[0mmaster\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0m_default_root\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3342\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mmaster\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3343\u001b[1;33m                 \u001b[1;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Too early to create image'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3344\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtk\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmaster\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'tk'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmaster\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3345\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mRuntimeError\u001b[0m: Too early to create image"
     ]
    }
   ],
   "source": [
    "loopCapture('masked_HighresScreenshot00071.png')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
